### ISSUE TITLE
Validate `ValidateTokenRequest#protocolVersion` parameter

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-server#1508]
The following property, `protocolVersion`, was added in 1.5.x, but not validated
https://github.com/wultra/powerauth-server/blob/30bfa16bbfda9f9b4e4ea02e498d75aa1becbeda/powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/model/request/ValidateTokenRequest.java#L37

As a result, implementors coming from older versions will have missing protocol versions in their requests and get `NullPointerException`.

```log
java.lang.NullPointerException: Cannot invoke "String.hashCode()" because "<local7>" is null
	at io.getlime.security.powerauth.crypto.lib.util.TokenUtils.computeTokenDigest(TokenUtils.java:104)
	at io.getlime.security.powerauth.crypto.lib.util.TokenUtils.validateTokenDigest(TokenUtils.java:124)
	at io.getlime.security.powerauth.crypto.server.token.ServerTokenVerifier.validateTokenDigest(ServerTokenVerifier.java:55)
	at io.getlime.security.powerauth.app.server.service.behavior.tasks.TokenBehavior.validateToken(TokenBehavior.java:316)
```

**Comment by banterCZ** [comment]
This should be backported to 1.5.x, 1.6.x and 1.7.x

**Comment by banterCZ** [comment]
Indeed, it was documented
> REST API Changes
The endpoint for PowerAuth token verification (see documentation), has been updated. A new parameter protocolVersion has been added. In case you invoke this endpoint from your backends, use need to use the version from PowerAuth HTTP header X-PowerAuth-Token received from mobile application, which contains the version which needs to be set as the new protocolVersion parameter.

But let's improve validation.
