### ISSUE TITLE
Cannot remove callbacks due to foreign key constraint

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-server#1722]
When trying to remove a callback URL, I get the following error:

```
Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table "pa_application_callback" violates foreign key constraint "pa_application_callback_id_fk" on table "pa_application_callback_event"
  Detail: Key (id)=(1c3ba2b2-f279-4265-87c9-c7ca8d22fabb) is still referenced from table "pa_application_callback_event".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2733) ~[postgresql-42.7.4.jar:42.7.4]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2420) ~[postgresql-42.7.4.jar:42.7.4]
	... 157 common frames omitted
```

The REST API method is `/rest/v3/application/callback/remove`.

**Comment by banterCZ** [comment]
Just an inspiration for soft-delete https://vladmihalcea.com/the-best-way-to-soft-delete-with-hibernate/
