### ISSUE TITLE
NPE in application detail when master keypair is missing

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-server#294]
Following NPE is thrown when application has been created outside of admin and it is missing the master keypair:

```
2019-03-27 15:45:56,487 [default task-11] ERROR i.g.s.p.a.s.s.v.PowerAuthServiceImpl - Unknown error occurred
java.lang.NullPointerException: null
    at io.getlime.security.powerauth.app.server.service.behavior.tasks.v3.ApplicationServiceBehavior.getApplicationDetail(ApplicationServiceBehavior.java:79)
    at io.getlime.security.powerauth.app.server.service.v3.PowerAuthServiceImpl.getApplicationDetail(PowerAuthServiceImpl.java:594)
    at io.getlime.security.powerauth.app.server.service.v3.PowerAuthServiceImpl$$FastClassBySpringCGLIB$$9b67a966.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
    at io.getlime.security.powerauth.app.server.service.v3.PowerAuthServiceImpl$$EnhancerBySpringCGLIB$$503d767e.getApplicationDetail(<generated>)
    at io.getlime.security.powerauth.app.server.endpoint.v3.PowerAuthEndpoint.getApplicationDetail(PowerAuthEndpoint.java:336)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)```

**Comment by petrdvorak** [comment]
The exception is correct status since the SOAP service always creates a valid application and all keys. However, I agree that NPE is not ideal...

**Comment by romanstrobl** [comment]
Yes, I wanted to replace NPE with some readable error.
