### ISSUE TITLE
Null pointer exception in ActivationOtpValidationConverter

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-server#413]
The error is:
```
Caused by: java.lang.NullPointerException: null
	at io.getlime.security.powerauth.app.server.database.model.ActivationOtpValidationConverter.convertToEntityAttribute(ActivationOtpValidationConverter.java:57) ~[classes/:0.24.0-SNAPSHOT]
	at io.getlime.security.powerauth.app.server.database.model.ActivationOtpValidationConverter.convertToEntityAttribute(ActivationOtpValidationConverter.java:29) ~[classes/:0.24.0-SNAPSHOT]
	at org.hibernate.metamodel.model.convert.internal.JpaAttributeConverterImpl.toDomainValue(JpaAttributeConverterImpl.java:45) ~[hibernate-core-5.4.12.Final.jar:5.4.12.Final]
```

**Comment by romanstrobl** [comment]
The issue was caused by invalid DB migration. Closing issue.
