### ISSUE TITLE
Insufficient input validation in activation prepare endpoint

### ISSUE THREAD

**Issue by hvge** [wultra/powerauth-server#762]
By accident I found a wrong input validation in `/rest/v3/activation/prepare` endpoint if mobile client doesn't send valid JSON in encrypted data. For example, if `devicePublicKey` is missing, then the following crash is reported:
```
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:889) ~[guava-31.0.1-jre.jar:na]
	at com.google.common.io.BaseEncoding$StandardBaseEncoding.trimTrailingPadding(BaseEncoding.java:675) ~[guava-31.0.1-jre.jar:na]
	at com.google.common.io.BaseEncoding.decodeChecked(BaseEncoding.java:232) ~[guava-31.0.1-jre.jar:na]
	at com.google.common.io.BaseEncoding.decode(BaseEncoding.java:217) ~[guava-31.0.1-jre.jar:na]
	at io.getlime.security.powerauth.app.server.service.behavior.tasks.v3.ActivationServiceBehavior.prepareActivation(ActivationServiceBehavior.java:888) ~[classes/:1.2.5]
	at io.getlime.security.powerauth.app.server.service.behavior.tasks.v3.ActivationServiceBehavior$$FastClassBySpringCGLIB$$ed6eb169.invoke(<generated>) ~[classes/:1.2.5]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.18.jar:5.3.18]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.3.18.jar:5.3.18]
	at io.getlime.security.powerauth.app.server.service.behavior.tasks.v3.ActivationServiceBehavior$$EnhancerBySpringCGLIB$$35bd738c.prepareActivation(<generated>) ~[classes/:1.2.5]
	at io.getlime.security.powerauth.app.server.service.v3.PowerAuthServiceImpl.prepareActivation(PowerAuthServiceImpl.java:314) ~[classes/:1.2.5]
	at io.getlime.security.powerauth.app.server.service.v3.PowerAuthServiceImpl$$FastClassBySpringCGLIB$$9b67a966.invoke(<generated>) ~[classes/:1.2.5]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.18.jar:5.3.18]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783) ~[spring-aop-5.3.18.jar:5.3.18]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.18.jar:5.3.18]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.18.jar:5.3.18]
        ...etc...
```

It's also strange that HTTP response is 500 (that's correct), but the formatted error doesn't fit to our specification:
```json
{
	"timestamp": "2022-09-08T19:21:03.132+00:00",
	"status": 500,
	"error": "Internal Server Error",
	"path": "/powerauth-java-server/rest/v3/activation/prepare"
}
```
I don't know if this is OK or not. The mobile client will perhaps properly get the correct error, due to an additional processing at RESTful integration layer.

**Comment by petrdvorak** [comment]
See also #9
