### ISSUE TITLE
Failing test testEncryptionAndDecryptionDifferentActivationFailServerPrivateKeyConverter

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-server#766]
Log message: 

```
ServerPrivateKeyConverterTest.testEncryptionAndDecryptionDifferentActivationFailServerPrivateKeyConverter:78 Expected io.getlime.security.powerauth.app.server.service.exceptions.GenericServiceException to be thrown, but nothing was thrown.
```

**Comment by banterCZ** [comment]
The test is not failing. I just see the following in the log.
```
etlime.security.powerauth.app.server.ServerPrivateKeyConverterTest
2023-07-31T11:26:29.018+02:00  WARN 31755 --- [           main] i.g.s.p.c.lib.util.AESEncryptionUtils    : pad block corrupted

javax.crypto.BadPaddingException: pad block corrupted
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$BufferedGenericBlockCipher.doFinal(Unknown Source) ~[bcprov-jdk18on-1.75.jar:1.75.0.0]
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(Unknown Source) ~[bcprov-jdk18on-1.75.jar:1.75.0.0]
	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2244) ~[na:na]
	at io.getlime.security.powerauth.crypto.lib.util.AESEncryptionUtils.decrypt(AESEncryptionUtils.java:102) ~[powerauth-java-crypto-1.5.0-SNAPSHOT.jar:na]
	at io.getlime.security.powerauth.crypto.lib.util.AESEncryptionUtils.decrypt(AESEncryptionUtils.java:125) ~[powerauth-java-crypto-1.5.0-SNAPSHOT.jar:na]
	at io.getlime.security.powerauth.app.server.converter.ServerPrivateKeyConverter.fromDBValue(ServerPrivateKeyConverter.java:126) ~[classes/:na]
	at io.getlime.security.powerauth.app.server.ServerPrivateKeyConverterTest.lambda$testEncryptionAndDecryptionDifferentActivationFailServerPrivateKeyConverter$1(ServerPrivateKeyConverterTest.java:82) ~[test-classes/:na]
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:53) ~[junit-jupiter-api-5.9.3.jar:5.9.3]
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35) ~[junit-jupiter-api-5.9.3.jar:5.9.3]
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3083) ~[junit-jupiter-api-5.9.3.jar:5.9.3]
	at io.getlime.security.powerauth.app.server.ServerPrivateKeyConverterTest.testEncryptionAndDecryptionDifferentActivationFailServerPrivateKeyConverter(ServerPrivateKeyConverterTest.java:79) ~[test-classes/:na]
```
