### ISSUE TITLE
 Admin: Embedded LDAP server is not provided

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-server#916]
Following error occurs when configuring LDAP in PowerAuth Admin.

```
	Caused by: java.lang.IllegalStateException: Embedded LDAP server is not provided
		at org.springframework.security.config.annotation.authentication.configurers.ldap.LdapAuthenticationProviderConfigurer$ContextSourceBuilder.startEmbeddedLdapServer(LdapAuthenticationProviderConfigurer.java:592)
		at org.springframework.security.config.annotation.authentication.configurers.ldap.LdapAuthenticationProviderConfigurer$ContextSourceBuilder.build(LdapAuthenticationProviderConfigurer.java:564)
```

It seems that an LDAP server dependency is missing.

**Comment by banterCZ** [comment]
Sorry, introduced by #904, see https://github.com/wultra/powerauth-server/pull/904/files#diff-05730f4c93412cf2ebd1185cb3a6d7ea3b6f5028b4d22f7704d74c3f8741f53dL47

**Comment by banterCZ** [comment]
Fixed by https://github.com/wultra/powerauth-server/commit/806e5925#diff-05730f4c93412cf2ebd1185cb3a6d7ea3b6f5028b4d22f7704d74c3f8741f53dR48
